import type { NextPage } from "next";
import Head from "next/head";
import NavBar from "../../components/NavBar";
import BlogTitle from "../../components/BlogTitle";
import Posts from "../../components/Posts";
import styles from "../../styles/Main.module.scss";

const Blog: NextPage = () => {
	return (
		<div className={styles.mainWrapper}>
			<Head>
				<title>artUserContact_blog</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<NavBar />
				<div className={styles.spacer}></div>
				<Posts />
			</main>
		</div>
	);
};

export default Blog;
